title: Andrey's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is Andrey Rainchik's blog. It mostly contains infosec-related posts,
  such as writeups for capture-the-flag competitions or, hopefully, any
  vulnerabilities I discover or exploits I develop.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andrey Rainchik # add your name
author-img: andrey.jpg # add your photo
about-author: I am a security consultant focusing on cloud services and web applications. Always looking for the next challenge. # add description
social-twitter: A_Rainchik # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: AndreyRainchik # add your Github handle
social-linkedin: andreyrainchik # add your Linkedin handle
social-email: andrey@rainchik.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
